/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_window2 (void);
GtkWidget* create_authentMeM (void);
GtkWidget* create_Ajouter (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_Gest_de_membres (void);
GtkWidget* create_filechooserdialog1 (void);
GtkWidget* create_Modifier (void);
GtkWidget* create_AfficherMem (void);
GtkWidget* create_SupprimerMeM (void);
GtkWidget* create_Membinter (void);
GtkWidget* create_success (void);
GtkWidget* create_window4 (void);
