/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *textview1;
  GtkWidget *entry1;
  GtkWidget *textview2;
  GtkWidget *entry2;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *checkbutton1;
  GtkWidget *textview3;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authentification), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (authentification), fixed1);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 656, 416);
  gtk_widget_set_size_request (button1, 104, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Sortie"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed1), textview1, 144, 200);
  gtk_widget_set_size_request (textview1, 80, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview1)), _("Identifiant:"), -1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 256, 192);
  gtk_widget_set_size_request (entry1, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_fixed_put (GTK_FIXED (fixed1), textview2, 136, 272);
  gtk_widget_set_size_request (textview2, 96, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview2)), _("Mot de passe"), -1);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 256, 264);
  gtk_widget_set_size_request (entry2, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 328, 376);
  gtk_widget_set_size_request (button2, 104, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Connecter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Je suis pas un robot"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 176, 328);
  gtk_widget_set_size_request (checkbutton1, 168, 24);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_fixed_put (GTK_FIXED (fixed1), textview3, 464, 328);
  gtk_widget_set_size_request (textview3, 168, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview3)), _("Mot de passe oubli\303\251e ?"), -1);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (authentification, button1, "button1");
  GLADE_HOOKUP_OBJECT (authentification, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (authentification, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (authentification, image1, "image1");
  GLADE_HOOKUP_OBJECT (authentification, label1, "label1");
  GLADE_HOOKUP_OBJECT (authentification, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (authentification, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (authentification, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (authentification, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (authentification, button2, "button2");
  GLADE_HOOKUP_OBJECT (authentification, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (authentification, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (authentification, image2, "image2");
  GLADE_HOOKUP_OBJECT (authentification, label2, "label2");
  GLADE_HOOKUP_OBJECT (authentification, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (authentification, textview3, "textview3");

  return authentification;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *textview4;
  GtkWidget *button3;
  GtkWidget *textview5;
  GtkWidget *button4;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  textview4 = gtk_text_view_new ();
  gtk_widget_show (textview4);
  gtk_fixed_put (GTK_FIXED (fixed2), textview4, 104, 96);
  gtk_widget_set_size_request (textview4, 264, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview4)), _("Connecter en tant qu'administrateur : "), -1);

  button3 = gtk_button_new_with_mnemonic (_("Cliquer ici"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 376, 88);
  gtk_widget_set_size_request (button3, 128, 32);

  textview5 = gtk_text_view_new ();
  gtk_widget_show (textview5);
  gtk_fixed_put (GTK_FIXED (fixed2), textview5, 144, 160);
  gtk_widget_set_size_request (textview5, 216, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview5)), _("Connecter en tant que membre :"), -1);

  button4 = gtk_button_new_with_mnemonic (_("Cliquer ici"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 376, 152);
  gtk_widget_set_size_request (button4, 128, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, textview4, "textview4");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, textview5, "textview5");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");

  return window2;
}

GtkWidget*
create_authentMeM (void)
{
  GtkWidget *authentMeM;
  GtkWidget *fixed3;
  GtkWidget *button5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *textview6;
  GtkWidget *entry3;
  GtkWidget *textview7;
  GtkWidget *entry4;
  GtkWidget *checkbutton2;
  GtkWidget *textview8;
  GtkWidget *button6;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;

  authentMeM = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authentMeM), _("auhentMeM"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (authentMeM), fixed3);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed3), button5, 584, 392);
  gtk_widget_set_size_request (button5, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  textview6 = gtk_text_view_new ();
  gtk_widget_show (textview6);
  gtk_fixed_put (GTK_FIXED (fixed3), textview6, 176, 200);
  gtk_widget_set_size_request (textview6, 80, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview6)), _("Identifiant:"), -1);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 296, 184);
  gtk_widget_set_size_request (entry3, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  textview7 = gtk_text_view_new ();
  gtk_widget_show (textview7);
  gtk_fixed_put (GTK_FIXED (fixed3), textview7, 160, 256);
  gtk_widget_set_size_request (textview7, 96, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview7)), _("Mot de passe:"), -1);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 296, 248);
  gtk_widget_set_size_request (entry4, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Je suis pas un robot"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 168, 304);
  gtk_widget_set_size_request (checkbutton2, 168, 24);

  textview8 = gtk_text_view_new ();
  gtk_widget_show (textview8);
  gtk_fixed_put (GTK_FIXED (fixed3), textview8, 488, 304);
  gtk_widget_set_size_request (textview8, 160, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview8)), _("Mot de passe oubli\303\251e ?"), -1);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed3), button6, 352, 344);
  gtk_widget_set_size_request (button6, 104, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button6), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Connecter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentMeM, authentMeM, "authentMeM");
  GLADE_HOOKUP_OBJECT (authentMeM, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (authentMeM, button5, "button5");
  GLADE_HOOKUP_OBJECT (authentMeM, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (authentMeM, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (authentMeM, image3, "image3");
  GLADE_HOOKUP_OBJECT (authentMeM, label3, "label3");
  GLADE_HOOKUP_OBJECT (authentMeM, textview6, "textview6");
  GLADE_HOOKUP_OBJECT (authentMeM, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (authentMeM, textview7, "textview7");
  GLADE_HOOKUP_OBJECT (authentMeM, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (authentMeM, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (authentMeM, textview8, "textview8");
  GLADE_HOOKUP_OBJECT (authentMeM, button6, "button6");
  GLADE_HOOKUP_OBJECT (authentMeM, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (authentMeM, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (authentMeM, image4, "image4");
  GLADE_HOOKUP_OBJECT (authentMeM, label4, "label4");

  return authentMeM;
}

GtkWidget*
create_Ajouter (void)
{
  GtkWidget *Ajouter;
  GtkWidget *fixed4;
  GtkWidget *textview9;
  GtkWidget *entry5;
  GtkWidget *textview10;
  GtkWidget *entry6;
  GtkWidget *textview11;
  GtkWidget *entry7;
  GtkWidget *textview12;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *textview13;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *button7;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *button8;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *textview14;
  GtkWidget *entry8;
  GtkWidget *textview19;
  GtkWidget *combobox1;

  Ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter), _("ajouter"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Ajouter), fixed4);

  textview9 = gtk_text_view_new ();
  gtk_widget_show (textview9);
  gtk_fixed_put (GTK_FIXED (fixed4), textview9, 136, 80);
  gtk_widget_set_size_request (textview9, 32, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview9)), _("CIN "), -1);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 200, 72);
  gtk_widget_set_size_request (entry5, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  textview10 = gtk_text_view_new ();
  gtk_widget_show (textview10);
  gtk_fixed_put (GTK_FIXED (fixed4), textview10, 112, 144);
  gtk_widget_set_size_request (textview10, 64, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview10)), _("Pr\303\251nom :"), -1);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 200, 136);
  gtk_widget_set_size_request (entry6, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  textview11 = gtk_text_view_new ();
  gtk_widget_show (textview11);
  gtk_fixed_put (GTK_FIXED (fixed4), textview11, 128, 200);
  gtk_widget_set_size_request (textview11, 48, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview11)), _("Nom :"), -1);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 200, 192);
  gtk_widget_set_size_request (entry7, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  textview12 = gtk_text_view_new ();
  gtk_widget_show (textview12);
  gtk_fixed_put (GTK_FIXED (fixed4), textview12, 40, 264);
  gtk_widget_set_size_request (textview12, 136, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview12)), _("Date de naissance :"), -1);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 200, 256);
  gtk_widget_set_size_request (spinbutton1, 56, 32);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 272, 256);
  gtk_widget_set_size_request (spinbutton2, 64, 32);

  spinbutton3_adj = gtk_adjustment_new (2010, 1960, 2017, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 352, 256);
  gtk_widget_set_size_request (spinbutton3, 88, 32);

  textview13 = gtk_text_view_new ();
  gtk_widget_show (textview13);
  gtk_fixed_put (GTK_FIXED (fixed4), textview13, 128, 328);
  gtk_widget_set_size_request (textview13, 40, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview13)), _("Sexe :"), -1);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton1, 208, 328);
  gtk_widget_set_size_request (radiobutton1, 104, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton2, 336, 328);
  gtk_widget_set_size_request (radiobutton2, 104, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed4), button7, 448, 520);
  gtk_widget_set_size_request (button7, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button7), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed4), button8, 592, 520);
  gtk_widget_set_size_request (button8, 104, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button8), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  textview14 = gtk_text_view_new ();
  gtk_widget_show (textview14);
  gtk_fixed_put (GTK_FIXED (fixed4), textview14, 16, 400);
  gtk_widget_set_size_request (textview14, 160, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview14)), _("Num\303\251ro de t\303\251l\303\251phone :"), -1);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 200, 392);
  gtk_widget_set_size_request (entry8, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  textview19 = gtk_text_view_new ();
  gtk_widget_show (textview19);
  gtk_fixed_put (GTK_FIXED (fixed4), textview19, 72, 456);
  gtk_widget_set_size_request (textview19, 104, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview19)), _("Cours sportif :"), -1);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1, 200, 448);
  gtk_widget_set_size_request (combobox1, 184, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Boxe "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Karat\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Physique"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Ajouter, textview9, "textview9");
  GLADE_HOOKUP_OBJECT (Ajouter, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Ajouter, textview10, "textview10");
  GLADE_HOOKUP_OBJECT (Ajouter, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Ajouter, textview11, "textview11");
  GLADE_HOOKUP_OBJECT (Ajouter, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Ajouter, textview12, "textview12");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Ajouter, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Ajouter, textview13, "textview13");
  GLADE_HOOKUP_OBJECT (Ajouter, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Ajouter, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Ajouter, button7, "button7");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Ajouter, image5, "image5");
  GLADE_HOOKUP_OBJECT (Ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (Ajouter, button8, "button8");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Ajouter, image6, "image6");
  GLADE_HOOKUP_OBJECT (Ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (Ajouter, textview14, "textview14");
  GLADE_HOOKUP_OBJECT (Ajouter, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Ajouter, textview19, "textview19");
  GLADE_HOOKUP_OBJECT (Ajouter, combobox1, "combobox1");

  return Ajouter;
}

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed5;
  GtkWidget *label7;
  GtkWidget *buttonacc;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *textview15;
  GtkWidget *textview16;
  GtkWidget *entry9;
  GtkWidget *button9;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label8;
  GtkWidget *button10;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label9;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed5);

  label7 = gtk_label_new (_("PAGE ADMINISTRATEURS"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed5), label7, 264, 40);
  gtk_widget_set_size_request (label7, 264, 16);

  buttonacc = gtk_check_button_new_with_mnemonic (_("Gestion de membres"));
  gtk_widget_show (buttonacc);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonacc, 240, 128);
  gtk_widget_set_size_request (buttonacc, 176, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Gestion des entaineurs"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton4, 240, 160);
  gtk_widget_set_size_request (checkbutton4, 192, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("Gestion d'\303\251quipements"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton5, 240, 192);
  gtk_widget_set_size_request (checkbutton5, 192, 24);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("Gestion des centres sportifs"));
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton6, 240, 224);
  gtk_widget_set_size_request (checkbutton6, 216, 24);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("Gestion des cours sportifs"));
  gtk_widget_show (checkbutton7);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton7, 240, 256);
  gtk_widget_set_size_request (checkbutton7, 216, 24);

  textview15 = gtk_text_view_new ();
  gtk_widget_show (textview15);
  gtk_fixed_put (GTK_FIXED (fixed5), textview15, 152, 88);
  gtk_widget_set_size_request (textview15, 176, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview15)), _("Choisissez votre gestion :"), -1);

  textview16 = gtk_text_view_new ();
  gtk_widget_show (textview16);
  gtk_fixed_put (GTK_FIXED (fixed5), textview16, 208, 320);
  gtk_widget_set_size_request (textview16, 104, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview16)), _("Mot de passe :"), -1);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed5), entry9, 328, 312);
  gtk_widget_set_size_request (entry9, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed5), button9, 560, 312);
  gtk_widget_set_size_request (button9, 104, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button9), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox7), label8, FALSE, FALSE, 0);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed5), button10, 696, 312);
  gtk_widget_set_size_request (button10, 96, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button10), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox8), label9, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (acceuil, label7, "label7");
  GLADE_HOOKUP_OBJECT (acceuil, buttonacc, "buttonacc");
  GLADE_HOOKUP_OBJECT (acceuil, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (acceuil, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (acceuil, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (acceuil, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (acceuil, textview15, "textview15");
  GLADE_HOOKUP_OBJECT (acceuil, textview16, "textview16");
  GLADE_HOOKUP_OBJECT (acceuil, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (acceuil, button9, "button9");
  GLADE_HOOKUP_OBJECT (acceuil, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (acceuil, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (acceuil, image7, "image7");
  GLADE_HOOKUP_OBJECT (acceuil, label8, "label8");
  GLADE_HOOKUP_OBJECT (acceuil, button10, "button10");
  GLADE_HOOKUP_OBJECT (acceuil, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (acceuil, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (acceuil, image8, "image8");
  GLADE_HOOKUP_OBJECT (acceuil, label9, "label9");

  return acceuil;
}

GtkWidget*
create_Gest_de_membres (void)
{
  GtkWidget *Gest_de_membres;
  GtkWidget *fixed6;
  GtkWidget *textview17;
  GtkWidget *tree1hayder;
  GtkWidget *textview18;
  GtkWidget *hayder1;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label19;
  GtkWidget *hayder2;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label18;
  GtkWidget *hayder3;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label17;
  GtkWidget *hayder4;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label16;
  GtkWidget *hayder5;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label15;
  GtkWidget *entry10;
  GtkWidget *button18;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label20;

  Gest_de_membres = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gest_de_membres), _("GestMeM"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Gest_de_membres), fixed6);

  textview17 = gtk_text_view_new ();
  gtk_widget_show (textview17);
  gtk_fixed_put (GTK_FIXED (fixed6), textview17, 344, 32);
  gtk_widget_set_size_request (textview17, 144, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview17)), _("Gestion des Membres"), -1);

  tree1hayder = gtk_tree_view_new ();
  gtk_widget_show (tree1hayder);
  gtk_fixed_put (GTK_FIXED (fixed6), tree1hayder, 56, 112);
  gtk_widget_set_size_request (tree1hayder, 192, 192);

  textview18 = gtk_text_view_new ();
  gtk_widget_show (textview18);
  gtk_fixed_put (GTK_FIXED (fixed6), textview18, 88, 64);
  gtk_widget_set_size_request (textview18, 104, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview18)), _("Les membres :"), -1);

  hayder1 = gtk_button_new ();
  gtk_widget_show (hayder1);
  gtk_fixed_put (GTK_FIXED (fixed6), hayder1, 448, 192);
  gtk_widget_set_size_request (hayder1, 136, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (hayder1), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox13), label19, FALSE, FALSE, 0);

  hayder2 = gtk_button_new ();
  gtk_widget_show (hayder2);
  gtk_fixed_put (GTK_FIXED (fixed6), hayder2, 272, 112);
  gtk_widget_set_size_request (hayder2, 136, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (hayder2), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox12), label18, FALSE, FALSE, 0);

  hayder3 = gtk_button_new ();
  gtk_widget_show (hayder3);
  gtk_fixed_put (GTK_FIXED (fixed6), hayder3, 272, 160);
  gtk_widget_set_size_request (hayder3, 136, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (hayder3), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  hayder4 = gtk_button_new ();
  gtk_widget_show (hayder4);
  gtk_fixed_put (GTK_FIXED (fixed6), hayder4, 272, 216);
  gtk_widget_set_size_request (hayder4, 136, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (hayder4), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox10), label16, FALSE, FALSE, 0);

  hayder5 = gtk_button_new ();
  gtk_widget_show (hayder5);
  gtk_fixed_put (GTK_FIXED (fixed6), hayder5, 272, 272);
  gtk_widget_set_size_request (hayder5, 136, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (hayder5), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Afficher tout..."));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox9), label15, FALSE, FALSE, 0);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 424, 112);
  gtk_widget_set_size_request (entry10, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed6), button18, 504, 344);
  gtk_widget_set_size_request (button18, 112, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button18), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox14), label20, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gest_de_membres, Gest_de_membres, "Gest_de_membres");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, textview17, "textview17");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, tree1hayder, "tree1hayder");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, textview18, "textview18");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hayder1, "hayder1");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, image13, "image13");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, label19, "label19");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hayder2, "hayder2");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, image12, "image12");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, label18, "label18");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hayder3, "hayder3");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, image11, "image11");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, label17, "label17");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hayder4, "hayder4");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, image10, "image10");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, label16, "label16");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hayder5, "hayder5");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, image9, "image9");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, label15, "label15");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, button18, "button18");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, image14, "image14");
  GLADE_HOOKUP_OBJECT (Gest_de_membres, label20, "label20");

  return Gest_de_membres;
}

GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *button16;
  GtkWidget *button17;

  filechooserdialog1 = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog1), 5);
  gtk_window_set_role (GTK_WINDOW (filechooserdialog1), "GtkFileChooserDialog");
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button16 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button16);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button16, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button17);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button17, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button16, "button16");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button17, "button17");

  gtk_widget_grab_default (button17);
  return filechooserdialog1;
}

GtkWidget*
create_Modifier (void)
{
  GtkWidget *Modifier;
  GtkWidget *fixed7;
  GtkWidget *textview20;
  GtkWidget *entry11;
  GtkWidget *textview21;
  GtkWidget *entry12;
  GtkWidget *textview22;
  GtkWidget *entry13;
  GtkWidget *textview23;
  GtkWidget *entry14;
  GtkWidget *combobox2;
  GtkWidget *textview24;
  GtkWidget *radiobutton3;
  GSList *radiobutton3_group = NULL;
  GtkWidget *button19;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label21;
  GtkWidget *button20;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label22;
  GtkWidget *textview35;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkWidget *textview36;
  GtkWidget *radiobutton10;
  GSList *radiobutton10_group = NULL;
  GtkWidget *radiobutton11;

  Modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier), _("Modifier"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Modifier), fixed7);

  textview20 = gtk_text_view_new ();
  gtk_widget_show (textview20);
  gtk_fixed_put (GTK_FIXED (fixed7), textview20, 128, 88);
  gtk_widget_set_size_request (textview20, 32, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview20)), _("CIN "), -1);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed7), entry11, 192, 80);
  gtk_widget_set_size_request (entry11, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  textview21 = gtk_text_view_new ();
  gtk_widget_show (textview21);
  gtk_fixed_put (GTK_FIXED (fixed7), textview21, 120, 144);
  gtk_widget_set_size_request (textview21, 48, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview21)), _("Nom :"), -1);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed7), entry12, 192, 136);
  gtk_widget_set_size_request (entry12, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  textview22 = gtk_text_view_new ();
  gtk_widget_show (textview22);
  gtk_fixed_put (GTK_FIXED (fixed7), textview22, 104, 192);
  gtk_widget_set_size_request (textview22, 72, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview22)), _("Pr\303\251nom :"), -1);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed7), entry13, 192, 192);
  gtk_widget_set_size_request (entry13, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  textview23 = gtk_text_view_new ();
  gtk_widget_show (textview23);
  gtk_fixed_put (GTK_FIXED (fixed7), textview23, 16, 256);
  gtk_widget_set_size_request (textview23, 160, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview23)), _("Num\303\251ro de t\303\251l\303\251phone :"), -1);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed7), entry14, 192, 248);
  gtk_widget_set_size_request (entry14, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox2, 192, 304);
  gtk_widget_set_size_request (combobox2, 184, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Musculation "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Boxe"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Karat\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Physique "));

  textview24 = gtk_text_view_new ();
  gtk_widget_show (textview24);
  gtk_fixed_put (GTK_FIXED (fixed7), textview24, 72, 312);
  gtk_widget_set_size_request (textview24, 96, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview24)), _("Cours sportif :"), -1);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("v\303\251rouiller"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton3, 408, 88);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  button19 = gtk_button_new ();
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed7), button19, 400, 488);
  gtk_widget_set_size_request (button19, 96, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button19), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox15), label21, FALSE, FALSE, 0);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed7), button20, 528, 488);
  gtk_widget_set_size_request (button20, 104, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button20), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox16), label22, FALSE, FALSE, 0);

  textview35 = gtk_text_view_new ();
  gtk_widget_show (textview35);
  gtk_fixed_put (GTK_FIXED (fixed7), textview35, 48, 376);
  gtk_widget_set_size_request (textview35, 136, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview35)), _("Date de naissance :"), -1);

  spinbutton10_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton10, 192, 368);
  gtk_widget_set_size_request (spinbutton10, 56, 32);

  spinbutton11_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton11, 264, 368);
  gtk_widget_set_size_request (spinbutton11, 64, 32);

  spinbutton12_adj = gtk_adjustment_new (2010, 1960, 2017, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton12, 344, 368);
  gtk_widget_set_size_request (spinbutton12, 88, 32);

  textview36 = gtk_text_view_new ();
  gtk_widget_show (textview36);
  gtk_fixed_put (GTK_FIXED (fixed7), textview36, 128, 432);
  gtk_widget_set_size_request (textview36, 40, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview36)), _("Sexe :"), -1);

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton10, 192, 424);
  gtk_widget_set_size_request (radiobutton10, 104, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton10_group);
  radiobutton10_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton11, 304, 424);
  gtk_widget_set_size_request (radiobutton11, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton3_group);
  radiobutton3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (Modifier, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Modifier, textview20, "textview20");
  GLADE_HOOKUP_OBJECT (Modifier, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (Modifier, textview21, "textview21");
  GLADE_HOOKUP_OBJECT (Modifier, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Modifier, textview22, "textview22");
  GLADE_HOOKUP_OBJECT (Modifier, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Modifier, textview23, "textview23");
  GLADE_HOOKUP_OBJECT (Modifier, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (Modifier, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (Modifier, textview24, "textview24");
  GLADE_HOOKUP_OBJECT (Modifier, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (Modifier, button19, "button19");
  GLADE_HOOKUP_OBJECT (Modifier, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Modifier, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Modifier, image15, "image15");
  GLADE_HOOKUP_OBJECT (Modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (Modifier, button20, "button20");
  GLADE_HOOKUP_OBJECT (Modifier, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Modifier, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Modifier, image16, "image16");
  GLADE_HOOKUP_OBJECT (Modifier, label22, "label22");
  GLADE_HOOKUP_OBJECT (Modifier, textview35, "textview35");
  GLADE_HOOKUP_OBJECT (Modifier, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (Modifier, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (Modifier, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (Modifier, textview36, "textview36");
  GLADE_HOOKUP_OBJECT (Modifier, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (Modifier, radiobutton11, "radiobutton11");

  return Modifier;
}

GtkWidget*
create_AfficherMem (void)
{
  GtkWidget *AfficherMem;
  GtkWidget *fixed8;
  GtkWidget *textview25;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview3;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *combobox3;
  GtkWidget *entry18;
  GtkWidget *button22;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label24;
  GtkWidget *button21;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label23;
  GtkWidget *button29;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label34;
  GtkWidget *label35;

  AfficherMem = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AfficherMem), _("afficher"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (AfficherMem), fixed8);

  textview25 = gtk_text_view_new ();
  gtk_widget_show (textview25);
  gtk_fixed_put (GTK_FIXED (fixed8), textview25, 40, 48);
  gtk_widget_set_size_request (textview25, 304, 16);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview25)), _("membres sont affiche\303\251s mais non accessible"), -1);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed8), scrolledwindow2, 32, 88);
  gtk_widget_set_size_request (scrolledwindow2, 560, 200);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview3);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Cacher ID"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton4, 96, 336);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Afficher ID"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton5, 264, 336);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Par cours sportif"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton6, 616, 120);
  gtk_widget_set_size_request (radiobutton6, 152, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Par ID"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton7, 616, 200);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox3, 640, 152);
  gtk_widget_set_size_request (combobox3, 112, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Musculation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Boxe "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Karat\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Gymnastique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Physique"));

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed8), entry18, 640, 248);
  gtk_widget_set_size_request (entry18, 136, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed8), button22, 704, 376);
  gtk_widget_set_size_request (button22, 112, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button22), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox18), label24, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed8), button21, 560, 376);
  gtk_widget_set_size_request (button21, 112, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button21), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Confirmer "));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox17), label23, FALSE, FALSE, 0);

  button29 = gtk_button_new ();
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed8), button29, 664, 296);
  gtk_widget_set_size_request (button29, 96, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button29), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox24), label34, FALSE, FALSE, 0);

  label35 = gtk_label_new (_("Filtrer"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed8), label35, 640, 80);
  gtk_widget_set_size_request (label35, 49, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AfficherMem, AfficherMem, "AfficherMem");
  GLADE_HOOKUP_OBJECT (AfficherMem, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (AfficherMem, textview25, "textview25");
  GLADE_HOOKUP_OBJECT (AfficherMem, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (AfficherMem, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (AfficherMem, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (AfficherMem, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (AfficherMem, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (AfficherMem, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (AfficherMem, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (AfficherMem, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (AfficherMem, button22, "button22");
  GLADE_HOOKUP_OBJECT (AfficherMem, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (AfficherMem, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (AfficherMem, image18, "image18");
  GLADE_HOOKUP_OBJECT (AfficherMem, label24, "label24");
  GLADE_HOOKUP_OBJECT (AfficherMem, button21, "button21");
  GLADE_HOOKUP_OBJECT (AfficherMem, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (AfficherMem, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (AfficherMem, image17, "image17");
  GLADE_HOOKUP_OBJECT (AfficherMem, label23, "label23");
  GLADE_HOOKUP_OBJECT (AfficherMem, button29, "button29");
  GLADE_HOOKUP_OBJECT (AfficherMem, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (AfficherMem, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (AfficherMem, image24, "image24");
  GLADE_HOOKUP_OBJECT (AfficherMem, label34, "label34");
  GLADE_HOOKUP_OBJECT (AfficherMem, label35, "label35");

  return AfficherMem;
}

GtkWidget*
create_SupprimerMeM (void)
{
  GtkWidget *SupprimerMeM;
  GtkWidget *fixed9;
  GtkWidget *textview26;
  GtkWidget *entry15;
  GtkWidget *textview27;
  GtkWidget *entry16;
  GtkWidget *button23;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label25;
  GtkWidget *button24;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label26;

  SupprimerMeM = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (SupprimerMeM), _("supprimer"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (SupprimerMeM), fixed9);

  textview26 = gtk_text_view_new ();
  gtk_widget_show (textview26);
  gtk_fixed_put (GTK_FIXED (fixed9), textview26, 96, 96);
  gtk_widget_set_size_request (textview26, 80, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview26)), _("Entrez l'ID :"), -1);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed9), entry15, 184, 88);
  gtk_widget_set_size_request (entry15, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  textview27 = gtk_text_view_new ();
  gtk_widget_show (textview27);
  gtk_fixed_put (GTK_FIXED (fixed9), textview27, 40, 152);
  gtk_widget_set_size_request (textview27, 392, 24);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview27)), _("Entrez votre Mot de passe pour confirmer la suppression :"), -1);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed9), entry16, 80, 200);
  gtk_widget_set_size_request (entry16, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed9), button23, 336, 200);
  gtk_widget_set_size_request (button23, 136, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button23), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Confirm"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox19), label25, FALSE, FALSE, 0);

  button24 = gtk_button_new ();
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed9), button24, 224, 280);
  gtk_widget_set_size_request (button24, 112, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button24), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox20), label26, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SupprimerMeM, SupprimerMeM, "SupprimerMeM");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, textview26, "textview26");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, textview27, "textview27");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, button23, "button23");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, image19, "image19");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, label25, "label25");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, button24, "button24");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, image20, "image20");
  GLADE_HOOKUP_OBJECT (SupprimerMeM, label26, "label26");

  return SupprimerMeM;
}

GtkWidget*
create_Membinter (void)
{
  GtkWidget *Membinter;
  GtkWidget *fixed10;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *entry17;
  GtkWidget *button27;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label32;
  GtkWidget *button28;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label33;
  GtkWidget *button25;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label29;
  GtkWidget *treeview4;
  GtkWidget *checkbutton8;
  GtkWidget *combobox5;
  GtkWidget *calendar1;
  GtkWidget *button32;

  Membinter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Membinter), _("interfaceMem"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (Membinter), fixed10);

  label27 = gtk_label_new (_("Demande un coach "));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed10), label27, 240, 24);
  gtk_widget_set_size_request (label27, 280, 48);

  label28 = gtk_label_new (_("Rechercher un coach :"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed10), label28, 96, 120);
  gtk_widget_set_size_request (label28, 168, 40);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed10), entry17, 264, 120);
  gtk_widget_set_size_request (entry17, 208, 40);
  gtk_editable_set_editable (GTK_EDITABLE (entry17), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  button27 = gtk_button_new ();
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed10), button27, 608, 608);
  gtk_widget_set_size_request (button27, 104, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button27), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox22), label32, FALSE, FALSE, 0);

  button28 = gtk_button_new ();
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed10), button28, 752, 616);
  gtk_widget_set_size_request (button28, 88, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button28), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox23), label33, FALSE, FALSE, 0);

  button25 = gtk_button_new ();
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed10), button25, 496, 120);
  gtk_widget_set_size_request (button25, 112, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button25), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox21), label29, FALSE, FALSE, 0);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview4, 360, 208);
  gtk_widget_set_size_request (treeview4, 360, 336);

  checkbutton8 = gtk_check_button_new_with_mnemonic (_("Par cours sportifs"));
  gtk_widget_show (checkbutton8);
  gtk_fixed_put (GTK_FIXED (fixed10), checkbutton8, 48, 192);
  gtk_widget_set_size_request (checkbutton8, 160, 24);

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed10), combobox5, 64, 232);
  gtk_widget_set_size_request (combobox5, 144, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Rami "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Ali"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Asma "));

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed10), calendar1, 56, 296);
  gtk_widget_set_size_request (calendar1, 253, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button32 = gtk_button_new_with_mnemonic (_("Choisir une date "));
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed10), button32, 96, 496);
  gtk_widget_set_size_request (button32, 152, 56);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Membinter, Membinter, "Membinter");
  GLADE_HOOKUP_OBJECT (Membinter, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Membinter, label27, "label27");
  GLADE_HOOKUP_OBJECT (Membinter, label28, "label28");
  GLADE_HOOKUP_OBJECT (Membinter, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (Membinter, button27, "button27");
  GLADE_HOOKUP_OBJECT (Membinter, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Membinter, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Membinter, image22, "image22");
  GLADE_HOOKUP_OBJECT (Membinter, label32, "label32");
  GLADE_HOOKUP_OBJECT (Membinter, button28, "button28");
  GLADE_HOOKUP_OBJECT (Membinter, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Membinter, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Membinter, image23, "image23");
  GLADE_HOOKUP_OBJECT (Membinter, label33, "label33");
  GLADE_HOOKUP_OBJECT (Membinter, button25, "button25");
  GLADE_HOOKUP_OBJECT (Membinter, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Membinter, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Membinter, image21, "image21");
  GLADE_HOOKUP_OBJECT (Membinter, label29, "label29");
  GLADE_HOOKUP_OBJECT (Membinter, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (Membinter, checkbutton8, "checkbutton8");
  GLADE_HOOKUP_OBJECT (Membinter, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (Membinter, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (Membinter, button32, "button32");

  return Membinter;
}

GtkWidget*
create_success (void)
{
  GtkWidget *success;
  GtkWidget *fixed11;
  GtkWidget *button33;
  GtkWidget *label37;

  success = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (success, 270, 130);
  gtk_window_set_title (GTK_WINDOW (success), _("succes"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (success), fixed11);

  button33 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed11), button33, 72, 64);
  gtk_widget_set_size_request (button33, 112, 48);

  label37 = gtk_label_new (_("Effectu\303\251 avec succ\303\251s!"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed11), label37, 48, 16);
  gtk_widget_set_size_request (label37, 168, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (success, success, "success");
  GLADE_HOOKUP_OBJECT (success, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (success, button33, "button33");
  GLADE_HOOKUP_OBJECT (success, label37, "label37");

  return success;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed12;
  GtkWidget *image26;
  GtkWidget *label38;
  GtkWidget *button34;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window4, 270, 130);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window4), fixed12);

  image26 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DND);
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed12), image26, 48, 32);
  gtk_widget_set_size_request (image26, 40, 40);

  label38 = gtk_label_new (_("   Une erreur\ns'est produite"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed12), label38, 96, 32);
  gtk_widget_set_size_request (label38, 97, 40);

  button34 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed12), button34, 80, 88);
  gtk_widget_set_size_request (button34, 96, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window4, image26, "image26");
  GLADE_HOOKUP_OBJECT (window4, label38, "label38");
  GLADE_HOOKUP_OBJECT (window4, button34, "button34");

  return window4;
}

