/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *authentification;
  GtkWidget *window2;
  GtkWidget *authentMeM;
  GtkWidget *Ajouter;
  GtkWidget *acceuil;
  GtkWidget *Gest_de_membres;
  GtkWidget *filechooserdialog1;
  GtkWidget *Modifier;
  GtkWidget *AfficherMem;
  GtkWidget *SupprimerMeM;
  GtkWidget *Membinter;
  GtkWidget *success;
  GtkWidget *window4;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  authentification = create_authentification ();
  gtk_widget_show (authentification);
  window2 = create_window2 ();
  gtk_widget_show (window2);
  authentMeM = create_authentMeM ();
  gtk_widget_show (authentMeM);
  Ajouter = create_Ajouter ();
  gtk_widget_show (Ajouter);
  acceuil = create_acceuil ();
  gtk_widget_show (acceuil);
  Gest_de_membres = create_Gest_de_membres ();
  gtk_widget_show (Gest_de_membres);
  filechooserdialog1 = create_filechooserdialog1 ();
  gtk_widget_show (filechooserdialog1);
  Modifier = create_Modifier ();
  gtk_widget_show (Modifier);
  AfficherMem = create_AfficherMem ();
  gtk_widget_show (AfficherMem);
  SupprimerMeM = create_SupprimerMeM ();
  gtk_widget_show (SupprimerMeM);
  Membinter = create_Membinter ();
  gtk_widget_show (Membinter);
  success = create_success ();
  gtk_widget_show (success);
  window4 = create_window4 ();
  gtk_widget_show (window4);

  gtk_main ();
  return 0;
}

