/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_page_d_acceuil_oussema (void);
GtkWidget* create_page_de_suppression (void);
GtkWidget* create_page_d_ajout (void);
GtkWidget* create_page_modification (void);
GtkWidget* create_page_d_inscription (void);
